name: CI

 on: [push]

 jobs:

 sast_scan:
 name: checkOut code
 uses: actions/checkout@v2

 name: set ou Python
 uses: actions/setup-python@v2
with: 
python-version: 3.8

name: Install Bandit
run: pip install bandit

name: Run Bandit Scan
run: bandit -r .
 
 

